test_average (__main__.TestExercice) ... FAIL
test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... FAIL
test_to_degrees (__main__.TestExercice) ... ERROR
test_to_farenheit (__main__.TestExercice) ... FAIL
test_to_radians (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 80, in test_to_degrees
    output = [exercice.to_degrees(v) for v in values]
  File "test_exercice.py", line 80, in <listcomp>
    output = [exercice.to_degrees(v) for v in values]
AttributeError: module 'exercice' has no attribute 'to_degrees'

======================================================================
ERROR: test_to_radians (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 61, in test_to_radians
    output = [exercice.to_radians(*v) for v in values]
  File "test_exercice.py", line 61, in <listcomp>
    output = [exercice.to_radians(*v) for v in values]
AttributeError: module 'exercice' has no attribute 'to_radians'

======================================================================
FAIL: test_average (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 47, in test_average
    self.assertListEqual(
AssertionError: Lists differ: [8.0, 8.0, 8.0] != [4.0, 0.0, -2.3333333333333335]

First differing element 0:
8.0
4.0

- [8.0, 8.0, 8.0]
+ [4.0, 0.0, -2.3333333333333335] : Mauvais calcul de la moyenne

======================================================================
FAIL: test_to_celsius (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 95, in test_to_celsius
    self.assertListEqual(
AssertionError: Lists differ: [232.77777777777777, 232.77777777777777, 232.77777777777777] != [-17.77777777777778, -31.666666666666664, 232.77777777777777]

First differing element 0:
232.77777777777777
-17.77777777777778

- [232.77777777777777, 232.77777777777777, 232.77777777777777]
+ [-17.77777777777778, -31.666666666666664, 232.77777777777777] : Mauvais calcul de farenheit -> celsius

======================================================================
FAIL: test_to_farenheit (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 107, in test_to_farenheit
    self.assertListEqual(
AssertionError: Lists differ: [212.0, 212.0, 212.0] != [32.0, -13.0, 843.8000000000001]

First differing element 0:
212.0
32.0

- [212.0, 212.0, 212.0]
+ [32.0, -13.0, 843.8000000000001] : Mauvais calcul de celsius -> farenheit

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=3, errors=2)
